adminpayreq:
    path:     /
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:index" }

adminpayreq_show:
    path:     /{id}/show
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:show" }

adminpayreq_new:
    path:     /new
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:new" }

adminpayreq_create:
    path:     /create
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:create" }
    requirements: { _method: post }

adminpayreq_edit:
    path:     /{id}/edit
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:edit" }

adminpayreq_update:
    path:     /{id}/update
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:update" }
    requirements: { _method: post|put }

adminpayreq_delete:
    path:     /{id}/delete
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AdminPayReq:delete" }
    requirements: { _method: post|delete }
