affiliatepayreq:
    path:     /
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:index" }

affiliatepayreq_show:
    path:     /{id}/show
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:show" }

affiliatepayreq_new:
    path:     /new
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:new" }

affiliatepayreq_create:
    path:     /create
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:create" }
    requirements: { _method: post }

affiliatepayreq_edit:
    path:     /{id}/edit
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:edit" }

affiliatepayreq_update:
    path:     /{id}/update
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:update" }
    requirements: { _method: post|put }

affiliatepayreq_delete:
    path:     /{id}/delete
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayReq:delete" }
    requirements: { _method: post|delete }
