affiliatepayrel:
    path:     /
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:index" }

affiliatepayrel_show:
    path:     /{id}/show
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:show" }

affiliatepayrel_new:
    path:     /new
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:new" }

affiliatepayrel_create:
    path:     /create
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:create" }
    requirements: { _method: post }

affiliatepayrel_edit:
    path:     /{id}/edit
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:edit" }

affiliatepayrel_update:
    path:     /{id}/update
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:update" }
    requirements: { _method: post|put }

affiliatepayrel_delete:
    path:     /{id}/delete
    defaults: { _controller: "AffiliateAffiliateManagementBundle:AffiliatePayRel:delete" }
    requirements: { _method: post|delete }
