affiliateinfo:
    path:     /
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:index" }

affiliateinfo_show:
    path:     /{id}/show
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:show" }

affiliateinfo_new:
    path:     /new
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:new" }

affiliateinfo_create:
    path:     /create
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:create" }
    requirements: { _method: post }

affiliateinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:edit" }

affiliateinfo_update:
    path:     /{id}/update
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:update" }
    requirements: { _method: post|put }

affiliateinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AffiliateAffiliateManagementBundle:Affiliateinfo:delete" }
    requirements: { _method: post|delete }
