affiliate_affiliate_management_homepage:
    path:     /hello/{name}
    defaults: { _controller: AffiliateAffiliateManagementBundle:Default:index }

AffiliateAffiliateManagementBundle_userinfo:
    resource: "@AffiliateAffiliateManagementBundle/Resources/config/routing/userinfo.yml"
    prefix:   /userinfo

##############################################
#AFFILIATE ROUTING START HERE#
##############################################
AffiliateAffiliateManagementBundle_deal:
    resource: "@AffiliateAffiliateManagementBundle/Resources/config/routing/deal.yml"
    prefix:   /deal
AffiliateAffiliateManagementBundle_affiliatedeal:
    resource: "@AffiliateAffiliateManagementBundle/Resources/config/routing/affiliatedeal.yml"
    prefix:   /affiliatedeal
AffiliateAffiliateManagementBundle_affiliatepayreq:
    resource: "@AffiliateAffiliateManagementBundle/Resources/config/routing/affiliatepayreq.yml"
    prefix:   /affiliatepayreq
##############################################
#AFFILIATE ROUTING END HERE#
##############################################

##############################################
#ADMIN ROUTING START HERE#
##############################################

AffiliateAffiliateManagementBundle_adminpayreq:
    resource: "@AffiliateAffiliateManagementBundle/Resources/config/routing/adminpayreq.yml"
    prefix:   /adminpayreq
##############################################
#ADMIN ROUTING END HERE#
##############################################

AffiliateAffiliateManagementBundle_membersinfo:
    resource: "@AffiliateAffiliateManagementBundle/Resources/config/routing/membersinfo.yml"
    prefix:   /membersinfo