affiliate_webservices_homepage:
    path:     /hello/{name}
    defaults: { _controller: AffiliateWebservicesBundle:Default:index }
affiliate_webservices_LoginService:
    path:     LoginService
    defaults: { _controller: AffiliateWebservicesBundle:LoginService:index }
affiliate_webservices_sign_up_user:
    path:     SignUpUser
    defaults: { _controller: AffiliateWebservicesBundle:SignUpUser:SignUpUser }
affiliate_webservices_members_listing:
    path:     /MembersListing
    defaults: { _controller: AffiliateWebservicesBundle:MembersListing:MembersListing }
affiliate_webservices_deal:
    path:     /Deal
    defaults: { _controller: AffiliateWebservicesBundle:Deal:Deal }
affiliate_webservices_affiliate_deal:
    path:     /AffiliateDeal
    defaults: { _controller: AffiliateWebservicesBundle:AffiliateDeal:AffiliateDeal }

affiliate_webservices_deal_listing:
    path:     /DealListing
    defaults: { _controller: AffiliateWebservicesBundle:DealListing:DealListing }

affiliate_webservices_admin_payment_request:
    path:     /AdminPaymentRequest
    defaults: { _controller: AffiliateWebservicesBundle:AdminPaymentRequest:AdminPaymentRequest }

affiliate_webservices_affiliate_payment_request:
    path:     /AffiliatePaymentRequest
    defaults: { _controller: AffiliateWebservicesBundle:AffiliatePaymentRequest:AffiliatePaymentRequest }

affiliate_webservices_edit_admin_payment_request:
    path:     /EditAdminPaymentRequest
    defaults: { _controller: AffiliateWebservicesBundle:EditAdminPaymentRequest:EditAdminPaymentRequest }

affiliate_webservices_listing_admin_pay_req:
    path:     /ListingAdminPayReq
    defaults: { _controller: AffiliateWebservicesBundle:ListingAdminPayReq:ListingAdminPayReq }

affiliate_webservices_edit_deal:
    path:     /EditDeal
    defaults: { _controller: AffiliateWebservicesBundle:EditDeal:EditDeal }

affiliate_webservices_edit_user_info:
    path:     /EditUserInfo
    defaults: { _controller: AffiliateWebservicesBundle:EditUserInfo:EditUserInfo }

affiliate_webservices_edit_affiliate_deal:
    path:     /EditAffiliateDeal
    defaults: { _controller: AffiliateWebservicesBundle:EditAffiliateDeal:EditAffiliateDeal }

_edit_affiliate_payment_request:
    path:     /EditAffiliatePaymentRequest
    defaults: { _controller: AffiliateWebservicesBundle:EditAffiliatePaymentRequest:EditAffiliatePaymentRequest }

_listing_affiliate_payment_request:
    path:     /ListingAffiliatePaymentRequest
    defaults: { _controller: AffiliateWebservicesBundle:ListingAffiliatePaymentRequest:ListingAffiliatePaymentRequest }
