<?php

namespace Affiliate\AffiliateManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembersinfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembersinfoRepository extends EntityRepository
{
}
