Affiliate\AffiliateManagementBundle\Entity\AdminPayReq:
    type: entity
    table: admin_payment_reqested_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\AdminPayReqRepository
    id:
        id:
            type: bigint
            admin_pay_req_id: true
            column: admin_pay_req_id
            generator:
                strategy: AUTO
    fields:
        requestedAmt:
            type: string
            length: '50'
            column: requested_amt
            nullable: true
        requestDate:
            type: datetime
            column: request_date
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
        reqStatus:
            type: string
            length: '20'
            column: req_status
            nullable: true
        createdat:
            type: datetime
            column: createdat
        updatedat:
            type: datetime
            column: updatedat
    manyToOne:
     Admin:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Admin
      inversedBy: AdminPayReq
      joinColumn:
        onDelete: "CASCADE"
        name: admin_id
        referencedColumnName: admin_id
     Userinfo:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AdminPayReq
      joinColumn:
        onDelete: "CASCADE"
        name: user_id
        referencedColumnName: user_id
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]