Affiliate\AffiliateManagementBundle\Entity\AdminPayReq:
    type: entity
    table: admin_payment_requested_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\AdminPayReqRepository
    id:
        id:
            type: bigint
            adminPayReqId: true
            column: adminPayReqId
            generator:
                strategy: AUTO
    fields:
        requestedAmt:
            type: string
            length: '50'
            column: requestedAmt
            nullable: true
        requestedDate:
            type: datetime
            column: requestedDate
            nullable: true
        reqDescription:
            type: string
            length: 255
            column: description
            nullable: true
        reqStatus:
            type: string
            length: '20'
            column: reqStatus
            nullable: true
        relDescription:
            type: string
            length: 255
            column: relDescription
            nullable: true
        relStatus:
            type: string
            length: '20'
            column: relStatus
            nullable: true
        releasedDate:
            type: datetime
            column: releasedDate
            nullable: true
        createdDate:
            type: datetime
            column: createdDate
        updatedDate:
            type: datetime
            column: updatedDate
    manyToOne:
     AdmininfoRequestedBy:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AdminAffiliatePayReq
      joinColumn:
        onDelete: "CASCADE"
        name: requestedBy
        referencedColumnName: userId
     AdmininfoReleasedBy:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AdminAffiliatePayRel
      joinColumn:
        onDelete: "CASCADE"
        name: releasedBy
        referencedColumnName: userId
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]