Affiliate\AffiliateManagementBundle\Entity\AdminPayRel:
    type: entity
    table: admin_payment_released_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\AdminPayRelRepository
    id:
        id:
            type: bigint
            admin_pay_rel_id: true
            column: admin_pay_rel_id
            generator:
                strategy: AUTO
    fields:
        releasedDate:
            type: datetime
        releasedAmt:
            type: string
            column: released_amt
            length: '50'
            nullable: true
        actualAmt:
            type: string
            column: actual_amt
            length: '50'
            nullable: true
        payMode:
            type: string
            column: pay_mode
            length: '50'
            nullable: true
        payStatus:
            type: string
            column: pay_status
            length: '50'
            nullable: true
        createdat:
            type: datetime
            column: createdat
        updatedat:
            type: datetime
            column: updatedat
    manyToOne:
     Admin:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Admin
      inversedBy: AdminPayRel
      joinColumn:
        onDelete: "CASCADE"
        name: admin_id
        referencedColumnName: admin_id
     Userinfo:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AdminPayRel
      joinColumn:
        onDelete: "CASCADE"
        name: user_id
        referencedColumnName: user_id
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]