Affiliate\AffiliateManagementBundle\Entity\AffiliateDeal:
    type: entity
    table: affiliate_deal_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\AffiliateDealRepository
    id:
        id:
            type: bigint
            affilDealId: true
            column: affilDealId
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 255
            column: description
            nullable: true
        createdDate:
            type: datetime
            column: createdDate
        updatedDate:
            type: datetime
            column: updatedDate
    manyToOne:
     Deal:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Deal
      inversedBy: AffiliateDeal
      joinColumn:
        onDelete: "CASCADE"
        name: dealId
        referencedColumnName: dealId
     Userinfo:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AffiliateDeal
      joinColumn:
        onDelete: "CASCADE"
        name: AffiliateId
        referencedColumnName: userId
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]