Affiliate\AffiliateManagementBundle\Entity\AffiliatePayReq:
    type: entity
    table: affiliate_payment_requested_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\AffiliatePayReqRepository
    id:
        id:
            type: bigint
            payReqId: true
            column: payReqId
            generator:
                strategy: AUTO
    fields:
        requestedAmt:
            type: string
            length: '50'
            column: requestedAmt
            nullable: true
        requestedDate:
            type: datetime
            column: requestedDate
            nullable: true
        reqDescription:
            type: string
            length: 255
            column: description
            nullable: true
        reqStatus:
            type: string
            length: '20'
            column: reqStatus
            nullable: true
        relDescription:
            type: string
            length: 255
            column: relDescription
            nullable: true
        relStatus:
            type: string
            length: '20'
            column: relStatus
            nullable: true
        releasedDate:
            type: datetime
            column: releasedDate
            nullable: true
        createdDate:
            type: datetime
            column: createdDate
        updatedDate:
            type: datetime
            column: updatedDate
    manyToOne:
     UserinfoRequestedBy:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AffiliatePayReq
      joinColumn:
        onDelete: "CASCADE"
        name: requestedBy
        referencedColumnName: userId
     UserinfoReleasedBy:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Userinfo
      inversedBy: AffiliatePayRel
      joinColumn:
        onDelete: "CASCADE"
        name: releasedBy
        referencedColumnName: userId
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]