Affiliate\AffiliateManagementBundle\Entity\Deal:
    type: entity
    table: deal_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\DealRepository
    id:
        id:
            type: bigint
            dealId: true
            column: dealId
            generator:
                strategy: AUTO
    fields:
        dName:
            type: string
            length: '30'
            column: dName
            nullable: true
        description:
            type: string
            length: 255
            column: description
            nullable: true
        dealDuration:
            type: string
            length: '20'
            column: dealDuration
            nullable: true
        createdDate:
            type: datetime
            column: createdDate
        updatedDate:
            type: datetime
            column: updatedDate
    oneToMany:
     AffiliateDeal:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\AffiliateDeal
      mappedBy: Deal
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]