Affiliate\AffiliateManagementBundle\Entity\Userinfo:
    type: entity
    table: userinfo_t
    repositoryClass: Affiliate\AffiliateManagementBundle\Entity\UserinfoRepository
    id:
        id:
            type: bigint
            userId: true
            column: userId
            generator:
                strategy: AUTO
    fields:
        fName:
            type: string
            length: '30'
            column: fName
            nullable: true
        lName:
            type: string
            length: '30'
            column: lName
            nullable: true
        userName:
            type: string
            length: '30'
            column: userName
            nullable: true
        password:
            type: string
            length: '100'
            column: password
            nullable: true
        email:
            type: string
            length: '30'
            column: email
            nullable: false
            unique: true
        city:
            type: string
            length: '20'
            column: city
            nullable: true
        state:
            type: string
            length: '20'
            column: state
            nullable: true
        country:
            type: string
            length: '20'
            column: country
            nullable: true
        zipCode:
            type: string
            length: '20'
            column: zipCode
            nullable: true
        mobile:
            type: string
            length: '20'
            column: mobile
            nullable: true
        userType:
            type: string
            length: '100'
            column: userType
            nullable: true
        deviceToken:
            type: string
            length: '100'
            column: deviceToken
            nullable: true
            unique: true
        addedBy:
            type: bigint
            column: addedBy
            nullable: true
        createdDate:
            type: datetime
            column: createdDate
        updatedDate:
            type: datetime
            column: updatedDate
    oneToMany:
     Membersinfo:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\Membersinfo
      mappedBy: Userinfo
     AffiliatePayReq:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\AffiliatePayReq
      mappedBy: UserinfoRequestedBy
     AffiliatePayRel:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\AffiliatePayReq
      mappedBy: UserinfoReleasedBy
     AdminAffiliatePayReq:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\AdminPayReq
      mappedBy: AdmininfoRequestedBy
     AdminAffiliatePayRel:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\AdminPayReq
      mappedBy: AdmininfoReleasedBy
     AffiliateDeal:
      targetEntity: Affiliate\AffiliateManagementBundle\Entity\AffiliateDeal
      mappedBy: Userinfo
    lifecycleCallbacks: 
      prePersist: [ setCreatedOnValue ]
      preUpdate: [ setUpdatedOnValue ]